- hosts: terraform-ansible-flask
  tasks:
    - name: go to project
      shell: "cd /home/ubuntu/flask_web_and_api"
    - name: adding project from github
      git:
        repo: "https://github.com/hernandemonteiro/flask_web_and_api.git"
        dest: /home/ubuntu/flask_web_and_api
        update: yes
        force: yes
        version: master
    - name: installing python3 and virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
      become: true
    - name: install pip dependencies
      pip:
        virtualenv: /home/ubuntu/flask_web_and_api/venv
        requirements: /home/ubuntu/flask_web_and_api/requirements.txt
    - name: restart flask_runner.service
      systemd:
        name: flask_runner
        state: restarted
      become: true
