name: Deploy Ansible AWS

on:
  push:
    branches:
    - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: go to path of files
      run: cd terraform_flask_run/ && pwd
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.FLASKTERRAFORM }}
      run: |
       echo "$SUPER_SECRET" > flask-terraform.pem
    - name: deploy via ansible
      run: ansible-playbook playbook.yml -u ubuntu --private-key flask-terraform.pem -i hosts.yml

