name: Deploy Ansible AWS

on:
  push:
    branches:
    - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: go to path of files
      run: cd terraform_flask_run/ && pwd
    - shell: bash
      run: sudo echo "$FLASK_AWS" > /terraform_flask_run/flask-terraform.pem
    - name: list folder
      run: cd terraform_flask_run/ && chmod 400 flask-terraform.pem && sudo cat flask-terraform.pem
    - name: deploy via ansible
      run: cd terraform_flask_run/ && ansible-playbook playbook.yml -u ubuntu --private-key flask-terraform.pem -i hosts.yml

