name: Deploy Ansible AWS

on:
  push:
    branches:
    - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: list src
      run: ls -la
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        directory: /home/runner/work/flask_web_and_api/flask_web_and_api/terraform_flask_run
        key: ${{secrets.FLASKTERRAFORM}}
        options: |
          --inventory .hosts
          --limit group1
          --extra-vars hello=there
          --verbose
